app = "fragkim-qdrant"
primary_region = "fra"

[build]
  image = "qdrant/qdrant:v1.12.4"

[env]
  QDRANT__SERVICE__HTTP_PORT = "6333"
  QDRANT__SERVICE__GRPC_PORT = "6334"

[mounts]
  source = "qdrant_data"
  destination = "/qdrant/storage"

[[services]]
  internal_port = 6333
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
